--
-- PostgreSQL database dump
--

\restrict GE9er18AFwPgvE9oWsrt9whmVBnKQBStyNL9zt9ycd3HWj6Ly4Imrs9Rw7UG74P

-- Dumped from database version 18.4
-- Dumped by pg_dump version 18.4

-- Started on 2026-07-23 21:54:28

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 226 (class 1259 OID 24610)
-- Name: portfolio; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.portfolio (
    id bigint NOT NULL,
    average_buy_price double precision NOT NULL,
    quantity integer NOT NULL,
    stock_id bigint,
    user_id bigint
);


ALTER TABLE public.portfolio OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 24609)
-- Name: portfolio_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.portfolio ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.portfolio_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 24577)
-- Name: stocks; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.stocks (
    id bigint NOT NULL,
    company_name character varying(255) NOT NULL,
    current_price double precision NOT NULL,
    market_cap bigint NOT NULL,
    sector character varying(255) NOT NULL,
    symbol character varying(255) NOT NULL
);


ALTER TABLE public.stocks OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 24576)
-- Name: stocks_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.stocks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.stocks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 24629)
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    transaction_time timestamp(6) without time zone NOT NULL,
    type character varying(255) NOT NULL,
    stock_id bigint,
    user_id bigint
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 24628)
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    full_name character varying(255) NOT NULL,
    password character varying(255) NOT NULL
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 24593)
-- Name: watchlist; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.watchlist (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    stock_id bigint,
    user_id bigint
);


ALTER TABLE public.watchlist OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 24592)
-- Name: watchlist_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.watchlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.watchlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5050 (class 0 OID 24610)
-- Dependencies: 226
-- Data for Name: portfolio; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.portfolio (id, average_buy_price, quantity, stock_id, user_id) FROM stdin;
1	1589.3029416976785	57	1	5
\.


--
-- TOC entry 5046 (class 0 OID 24577)
-- Dependencies: 222
-- Data for Name: stocks; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.stocks (id, company_name, current_price, market_cap, sector, symbol) FROM stdin;
1	Infosys	1625.5	6780000000000	IT	INFY
\.


--
-- TOC entry 5052 (class 0 OID 24629)
-- Dependencies: 228
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (id, price, quantity, transaction_time, type, stock_id, user_id) FROM stdin;
1	1625.5	1	2026-07-23 19:09:40.342954	BUY	1	5
\.


--
-- TOC entry 5044 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, email, full_name, password) FROM stdin;
5	manikanta1@gmail.com	Naga Manikanta	$2a$10$0oZqMH1yyElynqHAZMWbyuU5oHRvHS4D3PAWOSRsreJeapOzK6RHG
\.


--
-- TOC entry 5048 (class 0 OID 24593)
-- Dependencies: 224
-- Data for Name: watchlist; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.watchlist (id, created_at, stock_id, user_id) FROM stdin;
\.


--
-- TOC entry 5058 (class 0 OID 0)
-- Dependencies: 225
-- Name: portfolio_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.portfolio_id_seq', 1, true);


--
-- TOC entry 5059 (class 0 OID 0)
-- Dependencies: 221
-- Name: stocks_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.stocks_id_seq', 1, true);


--
-- TOC entry 5060 (class 0 OID 0)
-- Dependencies: 227
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, true);


--
-- TOC entry 5061 (class 0 OID 0)
-- Dependencies: 219
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 7, true);


--
-- TOC entry 5062 (class 0 OID 0)
-- Dependencies: 223
-- Name: watchlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.watchlist_id_seq', 2, true);


--
-- TOC entry 4887 (class 2606 OID 24617)
-- Name: portfolio portfolio_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio
    ADD CONSTRAINT portfolio_pkey PRIMARY KEY (id);


--
-- TOC entry 4881 (class 2606 OID 24589)
-- Name: stocks stocks_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT stocks_pkey PRIMARY KEY (id);


--
-- TOC entry 4889 (class 2606 OID 24638)
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- TOC entry 4883 (class 2606 OID 24591)
-- Name: stocks uk2oaank9l88k0ipjw48ua6fcty; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.stocks
    ADD CONSTRAINT uk2oaank9l88k0ipjw48ua6fcty UNIQUE (symbol);


--
-- TOC entry 4877 (class 2606 OID 16402)
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- TOC entry 4879 (class 2606 OID 16400)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4885 (class 2606 OID 24598)
-- Name: watchlist watchlist_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT watchlist_pkey PRIMARY KEY (id);


--
-- TOC entry 4892 (class 2606 OID 24623)
-- Name: portfolio fk76ws6sj6wg26k7lcx6a5mtqi4; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio
    ADD CONSTRAINT fk76ws6sj6wg26k7lcx6a5mtqi4 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4890 (class 2606 OID 24604)
-- Name: watchlist fkden7i83qo2swnr5br4wgc5r7j; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT fkden7i83qo2swnr5br4wgc5r7j FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4891 (class 2606 OID 24599)
-- Name: watchlist fkdfc609waltk8bqvm6wdyqlroh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.watchlist
    ADD CONSTRAINT fkdfc609waltk8bqvm6wdyqlroh FOREIGN KEY (stock_id) REFERENCES public.stocks(id);


--
-- TOC entry 4893 (class 2606 OID 24618)
-- Name: portfolio fkmu380nme3nldessk2l9dgkma; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.portfolio
    ADD CONSTRAINT fkmu380nme3nldessk2l9dgkma FOREIGN KEY (stock_id) REFERENCES public.stocks(id);


--
-- TOC entry 4894 (class 2606 OID 24644)
-- Name: transactions fkqwv7rmvc8va8rep7piikrojds; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkqwv7rmvc8va8rep7piikrojds FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- TOC entry 4895 (class 2606 OID 24639)
-- Name: transactions fkru6v24w1h01nvqoox4l2wkybv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkru6v24w1h01nvqoox4l2wkybv FOREIGN KEY (stock_id) REFERENCES public.stocks(id);


-- Completed on 2026-07-23 21:54:28

--
-- PostgreSQL database dump complete
--

\unrestrict GE9er18AFwPgvE9oWsrt9whmVBnKQBStyNL9zt9ycd3HWj6Ly4Imrs9Rw7UG74P

